name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "guides/**"
  pull_request:
    paths-ignore:
      - "guides/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  gleam:
    name: gleam ${{ matrix.gleam }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - gleam: "1.16.0"

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: ${{ matrix.gleam }}
          rebar3-version: "3"

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
